version: '3.5'
services:
  node:
    image: 'ghcr.io/fullstack-devops/docusaurus-dev-container:0.0.1'
    # user: 'node'
    working_dir: /home/node/app
    volumes:
      - ./docs:/home/node/app/docs
      - ./assets-ng-mat-components:/home/node/app/static/assets-ng-mat-components
    ports:
      - '3000:3000'
    entrypoint: ['sh', '-c', 'yarn install && yarn start']
