name: Build GH Pages Demo

on:
  push:
    branches:
      - "main"

jobs:
  build-gh-pages-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: install packages
        run: yarn
      - name: build workspace application
        run: yarn run build:workspace

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages-demo
          path: "gh-pages-demo"

      - name: Clean out old dist and copy new dist
        run: |
          rm -rf gh-pages-demo/dist/*
          cp -R dist/lib-workspace/* gh-pages-demo/dist

      - name: push chages to branch
        working-directory: gh-pages-demo
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git add .
          git status

          git commit -a -m "update dist automated by $GITHUB_ACTOR"
          git push
