name: Build PR

on:
  pull_request:

jobs:
  generate_infos:
    uses: fullstack-devops/git-workflows/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@fullstack-devops"

      - name: install packages
        run: yarn
      - name: build applikation
        run: |
          yarn version --new-version ${{ needs.generate_infos.outputs.version }}
          yarn run build

      - name: yarn publish
        working-directory: dist/ng-mat-components
        run: yarn publish --access public -dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
