name: Build PR

on:
  pull_request:

jobs:
  generate_infos:
    uses: fullstack-devops/git-workflows/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'
          scope: '@fullstack-devops'

      - name: install packages
        run: yarn
      - name: build applikation
        run: yarn run build
