name: Release Package

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'

jobs:
  create_release:
    uses: fullstack-devops/git-workflows/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node for GitHub
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@fullstack-devops'

      - name: install packages
        run: yarn
      - name: build applikation
        run: yarn run build

      - name: yarn publish
        working-directory: dist/ng-mat-components
        run: |
          npm version ${{ needs.create_release.outputs.version }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  publish_gh_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish release
        run: awesome-ci release publish --release-id "${{ needs.create_release.outputs.release-id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
