name: Release Package

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"

jobs:
  create_release:
    uses: fullstack-devops/actions/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup awesome-ci
        uses: fullstack-devops/awesome-ci-action@main
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@fullstack-devops"

      - name: install packages
        run: yarn
      - name: build applikation
        run: yarn run build

      - name: set publish config
        shell: bash
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: npm publish
        working-directory: dist/ng-mat-components
        run: |
          npm version ${{ needs.create_release.outputs.version }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        run: awesome-ci release publish -releaseid "${{ needs.create_release.outputs.releaseid }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
