name: Release Package

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE.md"

jobs:
  create_release:
    uses: fullstack-devops/git-workflows/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node for GitHub
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@fullstack-devops"

      - name: install packages
        run: yarn
      - name: build applikation
        run: |
          yarn version --new-version ${{ needs.create_release.outputs.version }} --cwd projects/ng-mat-components/ --no-git-tag-version
          yarn run build

      - name: yarn publish
        working-directory: dist/ng-mat-components
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish release
        run: awesome-ci release publish --release-id "${{ needs.create_release.outputs.release-id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
